apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: single-parakeet-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-hub/single-parakeet-dotnet-basic-gitops